import { defineConfig, type Plugin } from 'vite';
import { editorHead } from '../../tools/site/chrome.mjs';

/**
 * The editor lives at /app/ on webtoe.openaudiovisual.com; the homepage and
 * the docs around it are generated by tools/build-site.mjs into the same dist.
 * Its <head> (title, description, canonical, social cards, favicon, and the
 * analytics snippet once an ID is set in tools/site/config.mjs) comes from the
 * site's shared head partial, so the two never drift.
 */
function webtoeHead(): Plugin {
  let build = false;
  return {
    name: 'webtoe-head',
    configResolved(config) { build = config.command === 'build'; },
    transformIndexHtml(html) {
      return html.replace(/<!-- webtoe:head[\s\S]*?-->/, editorHead({ analytics: build }));
    },
  };
}

export default defineConfig({
  base: '/app/',
  build: { target: 'es2022', outDir: 'dist/app', emptyOutDir: true },
  server: { port: 8643, strictPort: true },
  plugins: [webtoeHead()],
});
