#!/usr/bin/env node
// Embed a small .wasm artifact as a base64 TS constant, so the kernel loads
// synchronously in both browsers and Node with no asset path to resolve.
// usage: node tools/embed-wasm.mjs <in.wasm> <out.ts> <EXPORT_NAME>
import { readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';

const [input, output, name] = process.argv.slice(2);
if (!input || !output || !name) {
  console.error('usage: node tools/embed-wasm.mjs <in.wasm> <out.ts> <EXPORT_NAME>');
  process.exit(2);
}
const bin = readFileSync(input);
const sha = createHash('sha256').update(bin).digest('hex').slice(0, 16);
writeFileSync(output,
  `// Generated by tools/embed-wasm.mjs from packages/wasm-kernels/${input} — do not edit.\n` +
  `// ${bin.length} bytes, sha256 ${sha}\n` +
  `export const ${name} =\n  '${bin.toString('base64')}';\n`);
console.log(`${output}: ${bin.length} bytes (sha256 ${sha})`);
